import SwiftUI

/// Root gate: first-run medical disclaimer, then Login or the main app, based on
/// `SessionStore.isLoggedIn`. Mirrors `Navigation.kt`'s `MainNavigation()` startup logic
/// (English-only disclaimer for Phase 1 — other languages plug in once localization lands).
struct ContentView: View {
    @EnvironmentObject private var session: SessionStore
    @State private var disclaimerAccepted = AppSettings.isDisclaimerAccepted

    var body: some View {
        Group {
            if !disclaimerAccepted {
                DisclaimerView {
                    AppSettings.isDisclaimerAccepted = true
                    disclaimerAccepted = true
                }
            } else if session.isLoggedIn {
                MainRootView()
            } else {
                LoginScreen()
            }
        }
    }
}

/// The post-login navigation shell: Home at the root, with Scan/Records/Report Detail pushed
/// on top via `AppRoute` — the SwiftUI analog of Navigation3's type-safe back stack.
private struct MainRootView: View {
    @State private var path = NavigationPath()

    var body: some View {
        NavigationStack(path: $path) {
            HomeScreen()
                .navigationDestination(for: AppRoute.self) { route in
                    switch route {
                    case .scan:
                        ScanScreen()
                    case .records:
                        RecordsScreen()
                    case .reportDetail(let id):
                        ReportDetailScreen(reportId: id)
                    case .smartHealthLens:
                        LiveVisionScreen()
                    case .doctorBrief(let patientName):
                        DoctorBriefScreen(patientName: patientName)
                    case .chat(let contextHint):
                        ChatScreen(context: contextHint)
                    case .reminders:
                        RemindersScreen()
                    case .medicationTracker:
                        MedicationTrackerScreen()
                    case .pendingTests:
                        PendingTestsScreen()
                    }
                }
        }
        #if DEBUG
        // Lets a debug build launch straight onto a screen for UI checks/screenshots:
        //   xcrun simctl launch <device> <bundle-id> -startAt records
        // Compiled out of release builds entirely.
        .onAppear {
            guard
                let index = ProcessInfo.processInfo.arguments.firstIndex(of: "-startAt"),
                index + 1 < ProcessInfo.processInfo.arguments.count
            else { return }
            switch ProcessInfo.processInfo.arguments[index + 1] {
            case "records": path.append(AppRoute.records)
            case "scan": path.append(AppRoute.scan)
            case "reminders": path.append(AppRoute.reminders)
            case "medications": path.append(AppRoute.medicationTracker)
            case "pendingTests": path.append(AppRoute.pendingTests)
            case "chat": path.append(AppRoute.chat(contextHint: "Records"))
            case "doctorBrief": path.append(AppRoute.doctorBrief(patientName: ""))
            default: break
            }
        }
        #endif
    }
}

private struct DisclaimerView: View {
    let onAccept: () -> Void

    var body: some View {
        VStack(spacing: 20) {
            Image(systemName: "exclamationmark.shield.fill")
                .font(.system(size: 48))
                .foregroundColor(.orange)
                .padding(.top, 40)
            Text("Before you continue")
                .font(.title2.bold())
            Text("""
            Medical Assist is not a medical device and does not provide medical advice, \
            diagnosis, or treatment. Information shown in this app — including anything \
            generated by AI — is for informational purposes only and is not a substitute for \
            professional medical judgment. Always consult a qualified doctor about your health.
            """)
            .font(.subheadline)
            .foregroundColor(.secondary)
            .multilineTextAlignment(.leading)
            .padding(.horizontal)
            Spacer()
            Button("I Understand") { onAccept() }
                .buttonStyle(.borderedProminent)
                .padding(.bottom, 40)
        }
        .padding()
    }
}

#Preview {
    ContentView().environmentObject(SessionStore())
}
